config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_website.urls' ))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_website/urls.py
from django.contrib import admin
from django.urls import path
from shop_website.views import views, auth
urlpatterns=[
    path('admin/',admin.site.urls),
    path('product-list/', views.product_list, name='product_list'),
    path('category/<slug:category_slug>/', views.product_list, name='category_detail_id'),
    path('pd/<int:product_id>', views.product_details, name='product_details'),
    path('product/<int:product_id>/add-comment/', views.add_comment, name='add_comment'),
    path('product/<int:product_id>/place-order/', views.place_order, name='place_order'),
    path('add-product/', views.add_product, name='add_product'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('login-page/', auth.login_page, name='login_page'),
    path('register-page/', auth.register_page, name='register_page'),
    path('logout-page/', auth.logout_page, name='logout_page'),


    


]

shop_website/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.html import mark_safe


class BaseModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

class Category(models.Model):
    title=models.CharField(max_length=70, unique=True)
    slug=models.SlugField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug=slugify(self.title)
        super(Category,self).save(*args, **kwargs)



    class Meta:
        verbose_name_plural='Categories'
        db_table='Category'

    def __str__(self) -> str:
        return self.title

class Product(BaseModel):
    class RatingChoices(models.IntegerChoices):
        zero = 0
        one = 1
        two = 2
        three = 3
        four = 4
        five = 5

    
    name=models.CharField(max_length=100)
    description=models.TextField(null=True, blank=True)
    price=models.FloatField()
    category=models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products')
    quantity=models.PositiveIntegerField(default=0)
    rating=models.PositiveIntegerField(choices=RatingChoices.choices, default=RatingChoices.zero.value)
    discount=models.PositiveIntegerField(default=0)
    image=models.ImageField(upload_to='products', default='sample_image.pg')
    slug=models.SlugField(null=True, blank=True)


    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug=slugify(self.name)
        super(Product,self).save(*args, **kwargs)



    class Meta:
        db_table='Product'


    
    def image_tag(self):
        return mark_safe('<img src="/products/%s" width="300" />' % (self.image))
    image_tag.short_description="Image"

    @property
    def discounted_price(self):
        if self.discount > 0:
            return int(self.price * (1-self.discount/100))
        return self.price

    def __str__(self):
        return self.name
    
    @property
    def get_image(self):
        if self.image:
            return self.image.url
        return None
        
        

# User degan table ham yaratilishi kerak #

# class User(models.Model):
#     name=models.CharField(max_length=100)
#     address=models.TextField()
#     phone_number=models.TextField()


# Create your models here.
class Comment(BaseModel):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    product=models.ForeignKey('Product', on_delete=models.CASCADE, related_name='comments')
    comment=models.TextField()
    is_provided=models.BooleanField(default=True)
    
    class Meta:
        db_table='Comment'

#     class Meta:
#         constraints = [
#             models.UniqueConstraint(fields=['product_id', 'user_id'], name='unique_product_user_comment')
#         ]

#     def __str__(self):
#         return f'Comment {self.comment_id} by {self.user_id} on {self.product_id}'

class Order(BaseModel):
    name=models.CharField(max_length=100)
    phone_number=models.CharField(max_length=13)
    product=models.ForeignKey('Product', on_delete=models.CASCADE, related_name='orders')
    order_quantity=models.PositiveIntegerField(default=0)

    def __str__(self):
        return (self.name + '' + self.phone_number)
    class Meta:
        db_table='Order'

#     class Meta:
#         constraints = [
#             models.UniqueConstraint(fields=['user_id'], name='unique_user_order')
#         ]




    

shop_website/forms.py
from django import forms 
from shop_website.models import Comment,Order, Product
from django.contrib.auth.models import User

class CommentModelForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields='__all__'
        # fields=['name, 'email, 'comment']
        exclude = ( 'product',)

    def clean_email(self):
        email=self.data.get('email')
        if Comment.objects.filter(email=email).exists():
            raise forms.ValidationError(f'This {email} was already used! ')
        return email


class OrderModelForm(forms.ModelForm):
    class Meta:
        model=Order
        exclude = ( 'product',)



class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields='__all__'




class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

    def clean_username(self):
        username=self.data.get('username')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'The user has not been found')
        return username


# class RegisterForm(forms.ModelForm):
#     # email=forms.EmailField(required=False)
#     confirm_password=forms.CharField(max_length=255)
#     class Meta:
#         model=User
#         fields=('username', 'password', 'email')

#     def clean_username(self):
#         username=self.cleaned_data.get('username')
#         if User.objects.filter(username=username).exists():
#             raise forms.ValidationError('This username already exists')
#         return username
    
#     def clean(self):
#         password=self.cleaned_data.get('password')
#         confirm_password=self.cleaned_data.get('confirm_password')
#         if password != confirm_password :
#             raise forms.ValidationError('Passwords do not match')
#         return password

class RegisterForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=255, label='Confirm Password')

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username already exists')
        return username

    # def clean_password(self):
    #     password = self.cleaned_data.get('password')
    #     confirm_password = self.cleaned_data.get('confirm_password')
    #     if password != confirm_password:
    #         raise forms.ValidationError('Passwords do not match')
    #     return password

    def clean(self):
        cleaned_data = super().clean()  # Call the parent's clean method
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
    
        if password and confirm_password and password != confirm_password:
            self.add_error('confirm_password', 'Passwords do not match')
    
        return cleaned_data  # Return all cleaned data


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # Use set_password to hash the password
        if commit:
            user.save()
        return user

shop_website/views/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404,redirect
from shop_website.models import Category, Product, Comment, Order
from typing import Optional
from shop_website.forms import CommentModelForm, OrderModelForm, ProductModelForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.
def product_list(request, category_slug: Optional[str]=None ):
    categories=Category.objects.all().order_by('id')
    search=request.GET.get('q')
    filter_type=request.GET.get('filter', '')
    if category_slug:
        if filter_type == 'expensive':
            products=Product.objects.filter(category__slug=category_slug).order_by('-price')
        elif filter_type=='cheap':
            products=Product.objects.filter(category__slug=category_slug).order_by('price')
        elif filter_type == 'quality_products':
             products=Product.objects.filter(Q(category__slug=category_slug) & Q(rating__gte=4)).order_by('-rating')
        else:
            products=Product.objects.filter(category__slug=category_slug)
            
    else:
        if filter_type == 'expensive':
            products=Product.objects.all().order_by('-price')
        elif filter_type=='cheap':
            products=Product.objects.all().order_by('price')
        elif filter_type == 'quality_products':
             products=Product.objects.filter(Q(rating__gte=4)).order_by('-rating')
        else:
            products = Product.objects.all()
    if search:
        products=products.filter(Q(name__icontains=search)| Q(comments__comment__icontains=search)).distinct()
    context={
    'products': products,
    'categories': categories 
    } 
    return render (request, 'shop_website/home.html', context)

# def product_details (request, product_id):
#     search=request.GET.get('q')
#     categories=Category.objects.all()
#     category_id=request.GET.get('category_id')
#     displayed_product_id=request.GET.get('displayed_product_id')
#     displayed_products=Product.objects.filter(category=category_id).exclude(id=displayed_product_id)
#     product=Product.objects.get(id=product_id)
#     comments=Comment.objects.filter(product=product_id, is_provided=True).order_by('-id')
#     if search:
#         comments=comments.filter(Q(comment__icontains=search))
#         # if not related to only one product, but for all products:
#         # comments=Comment.objects.filter(Q(comment__icontains=search))
#     context={
#         'product': product,
#         'displayed_products': displayed_products,
#         'comments': comments,
#         'categories': categories, 
#         }
#     return render (request, 'shop_website/detail.html', context)

def product_details (request, product_id):
    search=request.GET.get('q')
    categories=Category.objects.all()
    product=Product.objects.get(id=product_id)
    min_price = product.price * 0.2
    max_price = product.price * 2
    comments=Comment.objects.filter(product=product_id, is_provided=True).order_by('-id')
    
    if product:
        displayed_products=Product.objects.filter(category=product.category, price__range=(min_price, max_price,)).exclude(id=product_id)
# range accepts either a list or a tuple
    
    if search:
        comments=comments.filter(Q(comment__icontains=search))
        # if not related to only one product, but for all products:
        # comments=Comment.objects.filter(Q(comment__icontains=search))
    context={
        'product': product,
        'displayed_products': displayed_products,
        'comments': comments,
        'categories': categories, 
        }
    return render (request, 'shop_website/detail.html', context)



# def add_comment(request, product_id):
    product=get_object_or_404(Product, id=product_id)
    if request.method=='POST':
        name=request.POST.get('name')
        email=request.POST.get('email')
        comment=request.POST.get('comment')
        user_comment=Comment(name=name, email=email, comment=comment)
        user_comment.product=product
        user_comment.save()
        return redirect ('product_details', product_id)
    else:
        pass
    return render(request, 'shop_website/detail.html')

def add_comment(request, product_id):
    product=get_object_or_404(Product, id=product_id)
    if request.method=='POST':
        form=CommentModelForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.product=product
            comment.save()
            return redirect('product_details', product_id)
    else:
        form=CommentModelForm()
    context={
        'form':form,
        'product': product
    }

    return render(request, 'shop_website/detail.html', context )


# PLACE ORDER HttpResponseRedireect bilan

def place_order(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, id=product_id)
        form = OrderModelForm(request.POST or None)
        order_quantity = int(request.POST.get('order_quantity', 0))

        if form.is_valid():
            order = form.save(commit=False)
            order.product = product
            
            
            if order_quantity > 0 and order_quantity <= product.quantity:
                order = Order.objects.create(
                name=request.POST.get('name'),
                phone_number=request.POST.get('phone_number'),
                product=product,
                order_quantity=order_quantity
                    )
                product.quantity -= order_quantity
                order.save()
                messages.success(request, 'Your order has been secured!')
                product.save()
                positive_message= HttpResponseRedirect('/success/')
                print(positive_message)
                return redirect('product_list')
               
    
            else:
                messages.error(request, 'Your order does not fit the storage capability')
                negative_message=HttpResponseRedirect('/error')
                print(negative_message)
                form=CommentModelForm()

    context = {
        'form': form,
        'product': product
            }
    return render(request, 'shop_website/detail.html', context)





# PLACE ORDER messages.add_message bilan

# def place_order(request, product_id):
#     product = get_object_or_404(Product, id=product_id)
#     form=OrderModelForm()

#     if request.method=='POST':
#         form=OrderModelForm(request.POST)
#         if form.is_valid():
#             order=form.save(commit=False)
#             order.product=product
#             if product.quantity >= order.order_quantity:
#                 product.quantity -= order.order_quantity
#                 order.save()
#                 product.save()
#                 messages.add_message(
#                     request, 
#                     level=messages.SUCCESS,
#                     message='Your order has been sucessfully saved!'
#                 )
#                 return redirect('product_details', product_id)
#             else:
#                 messages.add_message(
#                     request, 
#                     level=messages.ERROR,
#                     message = 'Insufficient storage'
#                 )
        
#     context= {
#         'form': form,
#         'product': product
#         }
        
#     return render(request, 'shop_website/detail.html',context)

@login_required
def add_product(request):
    form=ProductModelForm()
    if request.method=='POST':
        form=ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    
    context={
        'form':form
    }

    return render (request, 'shop_website/add_product.html', context)


@login_required
def delete_product(request, product_id):
    product=get_object_or_404(Product, id=product_id)
    if product:
        product.delete()
        return redirect('product_list')
        
@login_required
def edit_product(request, product_id):
    product=get_object_or_404(Product, id=product_id)
    form=ProductModelForm(instance=product)
    if request.method=='POST':
        form=ProductModelForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_details', product_id)
        
    context={
            'form':form
            }

    return render (request, 'shop_website/edit-product.html', context)

# def related_products(request, category_id, displayed_product_id):
#     category=get_object_or_404(Category, id=category_id)
#     products=Product.objects(category=category).exclude(id=displayed_product_id)
#     context={
#         'category':category,
#         'products':products,
#     }
#     return render (request, 'shop_website/detail.html', context)

shop_website/templates/shop_website/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> ADD PRODUCT </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <form method="post"  enctype="multipart/form-data" > 
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-info">Send</button>


    </form>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

shop_website/templates/shop_website/detail.html
{% extends 'shop_website/base/base.html' %}
{% load static %}
{%  block title %} Product Detail {% endblock%}
{% block detail_content %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1"> Quantity: {{product.quantity}}
                    
                </div>
                <div>
                    <a href="{% url 'delete_product' product.id %}" id="delete-link">
                        <button type="button" class="btn btn-danger" onclick="return confirmDelete();">Delete</button>
                    </a>
                    
                    <script type="text/javascript">
                        function confirmDelete() {
                            var isValid = confirm('Are you sure?');
                            if (!isValid) {
                                alert("It won't delete. Yay!");
                                return false;
                            }
                            return true; 
                        }
                    </script>
                    
                    <a href="{% url 'edit_product' product.id %}">
                    <button type="submit" class="btn btn-secondary"> Edit </button>
                    
                    </a>
                </div>
                <h1 class="display-5 fw-bolder">{{ product.name}}</h1>
                <div class="fs-5 mb-5">
                    {% if product.discount > 0 %}
                                        <span class="text-muted text-decoration-line-through">
                                        ${{product.price}} </span>
                                        ${{product.discounted_price}}
                                    {% else%}
                                        ${{product.price}}
                                    {% endif %}
                </div>
                <p class="lead">{{ product.description}}</p>
                <div class="d-flex">
                    <form method="post" action="{% url 'place_order' product.id %}">
                        {% csrf_token %} 
                        <div class="form-group"> 
                            <h2>Place an order</h2>
                        </div>
                        <div> 
                            <ul>
                                {% for message in messages %}
                                    {% if 'error' in message.tags %}
                                        <li style="color:red"> 
                                            {{message}}
                                        </li>
                                    {% elif 'succes' in message.tags %}
                                        <li  style="color:green">
                                            {{message}} 
                                        </li>
                                    {% endif %}
                                {% endfor %}


                            </ul>
                        </div>
                        <div class="form-group mb-3">
                          <label for="formGroupExampleInput">Your name</label>
                          <input type="text" class="form-control" name="name" value="{{ form.name.value|default:'' }}" placeholder="Your name" required>
                        </div>
                        <div class="form-group mb-3">
                          <label for="formGroupExampleInput2">Your phone</label>
                          <input type="text" class="form-control" name="phone_number" value="{{ form.phone_number.value|default:'' }}" placeholder="Your phone" required>
                        </div>
                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput2"> Quantity </label>
                            <input type="number" class="form-control" name="order_quantity" value="{{ form.order_quantity.value|default:'' }}" placeholder="How many products?" required>
                        </div>
  

                       

                          <div class="form-group mb-3">
                           
                            <input type="submit" class="btn btn-success" value="Send">
                          </div>
                      </form>
                   
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container mt-4 mb-4">
    <div class="row">
        <div class="col-12">
            <div class="text-center">
                <h2>Latest comments ({{product.comments.count}})</h2>
            </div>
            {% for comment in comments %}
                <div class="media card p-4 mt-2">
                    <div class="media-body">
                    <h4 class="mt-0"> {{comment.name}} <mark> {{comment.created_at}} </mark></h4>
                    <br>

                    <h5 class="mt-0"> {{comment.comment}} </h5>
                    </div>
                </div>
            {% endfor %}

        </div>

        <div class="col-8 offset-2 mt-5">
            <div class="p-5">
                <div class="text-center">
                    <h3>Add Comment</h3>
                </div>
                <div>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger"> 
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </div>
        
                <form method="post" action="{% url 'add_comment' product.id %}">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="id_name">Your name</label>
                        <input type="text" class="form-control" name="name" value="{{ form.name.value|default:'' }}" placeholder="Your name">
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_email">Your email</label>
                        <input type="text" class="form-control" name="email" value="{{ form.email.value|default:'' }}" placeholder="Your email">
                    </div>
        
                    <div class="form-group mb-3">
                        <label for="id_comment">Your comment</label>
                        <textarea name="comment" class="form-control" cols="30" rows="10">{{ form.comment.value|default:'' }}</textarea>
                    </div>
        
                    <div class="form-group mb-3">
                        <input type="submit" class="btn btn-success" value="Send">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Related products</h2>
        
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in displayed_products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    {% if product.discount > 0 %}
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    {% endif %}
                    <!-- Product image-->
                    {% if product.image %}
                        <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                    {% else %}
                        <img class="card-img-top" src="{% static 'path/to/default/image.jpg' %}" alt="Default Image" />
                    {% endif %}

                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                {% with ''|center:product.rating as ratings %}
                                    {%  for rating in ratings %}
                                        <div class="bi-star-fill"></div>
                                    {% endfor %}
                                {% endwith %}
                    
                            </div>
                            <!-- Product price-->
                            
                                {% if product.discount > 0 %}
                                    <span class="text-muted text-decoration-line-through">
                                    ${{product.price}} </span>
                                    ${{product.discounted_price}}
                                {% else%}
                                    ${{product.price}}
                                {% endif %}
                            
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_details' product.id  %}">View product</a></div>
                    </div>
                  
                    
                </div>

            </div>
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

shop_website/templates/shop_website/edit-product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Product</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success"> Edit </button>

</form>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>